package au.com.telstra.team;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "estimate")
public class Estimate implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ESTIMATE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "ESTIMATE_ID_GENERATOR", sequenceName = "ESTIMATE_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("EstimatedType")
	private java.lang.String estimatedType;

	@org.kie.api.definition.type.Label("EstimatedCost")
	private java.lang.String estimatedCost;

	@org.kie.api.definition.type.Label("VarianceCost")
	private java.lang.String varianceCost;

	@org.kie.api.definition.type.Label("OverheadCost")
	private java.lang.String overheadCost;

	@org.kie.api.definition.type.Label("Comments")
	private java.lang.String comments;

	public Estimate() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getEstimatedType() {
		return this.estimatedType;
	}

	public void setEstimatedType(java.lang.String estimatedType) {
		this.estimatedType = estimatedType;
	}

	public java.lang.String getEstimatedCost() {
		return this.estimatedCost;
	}

	public void setEstimatedCost(java.lang.String estimatedCost) {
		this.estimatedCost = estimatedCost;
	}

	public java.lang.String getVarianceCost() {
		return this.varianceCost;
	}

	public void setVarianceCost(java.lang.String varianceCost) {
		this.varianceCost = varianceCost;
	}

	public java.lang.String getOverheadCost() {
		return this.overheadCost;
	}

	public void setOverheadCost(java.lang.String overheadCost) {
		this.overheadCost = overheadCost;
	}

	public java.lang.String getComments() {
		return this.comments;
	}

	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	public Estimate(java.lang.Long id, java.lang.String estimatedType,
			java.lang.String estimatedCost, java.lang.String varianceCost,
			java.lang.String overheadCost, java.lang.String comments) {
		this.id = id;
		this.estimatedType = estimatedType;
		this.estimatedCost = estimatedCost;
		this.varianceCost = varianceCost;
		this.overheadCost = overheadCost;
		this.comments = comments;
	}

}