package au.com.telstra.team;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "financialdetail")
public class FinancialDetail implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "FINANCIALDETAIL_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "FINANCIALDETAIL_ID_GENERATOR", sequenceName = "FINANCIALDETAIL_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("FundingCategory")
	private java.lang.String fundingcategory;

	@org.kie.api.definition.type.Label("FundingType")
	private java.lang.String fundingtype;

	@org.kie.api.definition.type.Label("FundingRequiredByDate")
	private java.lang.String fundingrequiredbydate;

	@org.kie.api.definition.type.Label("Comments")
	private java.lang.String comments;

	@javax.persistence.Column(name = "estimates")
	@org.kie.api.definition.type.Label("Estimates")
	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {
			javax.persistence.CascadeType.ALL,
			javax.persistence.CascadeType.PERSIST}, orphanRemoval = false)
	private java.util.List<au.com.telstra.team.Estimate> estimates;

	public FinancialDetail() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getFundingcategory() {
		return this.fundingcategory;
	}

	public void setFundingcategory(java.lang.String fundingcategory) {
		this.fundingcategory = fundingcategory;
	}

	public java.lang.String getFundingtype() {
		return this.fundingtype;
	}

	public void setFundingtype(java.lang.String fundingtype) {
		this.fundingtype = fundingtype;
	}

	public java.lang.String getFundingrequiredbydate() {
		return this.fundingrequiredbydate;
	}

	public void setFundingrequiredbydate(java.lang.String fundingrequiredbydate) {
		this.fundingrequiredbydate = fundingrequiredbydate;
	}

	public java.lang.String getComments() {
		return this.comments;
	}

	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	public java.util.List<au.com.telstra.team.Estimate> getEstimates() {
		return this.estimates;
	}

	public void setEstimates(
			java.util.List<au.com.telstra.team.Estimate> estimates) {
		this.estimates = estimates;
	}

	public FinancialDetail(java.lang.Long id, java.lang.String fundingcategory,
			java.lang.String fundingtype,
			java.lang.String fundingrequiredbydate, java.lang.String comments,
			java.util.List<au.com.telstra.team.Estimate> estimates) {
		this.id = id;
		this.fundingcategory = fundingcategory;
		this.fundingtype = fundingtype;
		this.fundingrequiredbydate = fundingrequiredbydate;
		this.comments = comments;
		this.estimates = estimates;
	}

}