package au.com.telstra.team;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Project implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROJECT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PROJECT_ID_GENERATOR", sequenceName = "Project_id_seq")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Number")
	private java.lang.String number;

	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label("SubType")
	private java.lang.String subType;
	@org.kie.api.definition.type.Label(value = "Status")
	private java.lang.String status;
	public Project() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getNumber() {
		return this.number;
	}

	public void setNumber(java.lang.String number) {
		this.number = number;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getSubType() {
		return this.subType;
	}

	public void setSubType(java.lang.String subType) {
		this.subType = subType;
	}
	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public Project(java.lang.Long id, java.lang.String name,
			java.lang.String number, java.lang.String type,
			java.lang.String subType, java.lang.String status) {
		this.id = id;
		this.name = name;
		this.number = number;
		this.type = type;
		this.subType = subType;
		this.status = status;
	}

}