package au.com.telstra.team;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Site implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SITE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "SITE_ID_GENERATOR", sequenceName = "SITE_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Latitude")
	private java.lang.String latitude;

	@org.kie.api.definition.type.Label("Longitude")
	private java.lang.String longitude;

	@org.kie.api.definition.type.Label("AreaType")
	private java.lang.String areaType;

	@org.kie.api.definition.type.Label("Office")
	private java.lang.String office;

	@org.kie.api.definition.type.Label("Technology")
	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<java.lang.String> technology;

	@org.kie.api.definition.type.Label("State")
	private String state;

	public Site() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(java.lang.String latitude) {
		this.latitude = latitude;
	}

	public java.lang.String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(java.lang.String longitude) {
		this.longitude = longitude;
	}

	public java.lang.String getAreaType() {
		return this.areaType;
	}

	public void setAreaType(java.lang.String areaType) {
		this.areaType = areaType;
	}

	public java.lang.String getOffice() {
		return this.office;
	}

	public void setOffice(java.lang.String office) {
		this.office = office;
	}

	public java.util.List<java.lang.String> getTechnology() {
		return this.technology;
	}

	public void setTechnology(java.util.List<java.lang.String> technology) {
		this.technology = technology;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public Site(java.lang.Long id, java.lang.String name,
			java.lang.String latitude, java.lang.String longitude,
			java.lang.String areaType, java.lang.String office,
			java.util.List<java.lang.String> technology, java.lang.String state) {
		this.id = id;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
		this.areaType = areaType;
		this.office = office;
		this.technology = technology;
		this.state = state;
	}

}